DATE := `date +%Y-%m-%d`
IMAGE_NAME := 'menu-app:' + DATE

build:
    podman pull python:3.14-alpine ghcr.io/astral-sh/uv:python3.14-alpine
    [ -n "${REGISTRY:-}" ] || { echo >&2 "REGISTRY is not set"; exit 1; }
    podman build -t {{IMAGE_NAME}} .
    podman tag {{IMAGE_NAME}} ${REGISTRY}/$(whoami)/{{IMAGE_NAME}}
